# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# English menu
main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: research
    weight: 20
  - name: Projects
    url: project
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Contact
    url: contact
    weight: 50
